### ISSUE TITLE
docker安装部署报无法找到数据包或者视图

### ISSUE THREAD

**Issue by wdsjxh** [hack2012/xssblind#1]
Fatal error: Uncaught PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'ezxss.settings' doesn't exist in /var/www/html/src/Database.php:107 Stack trace: #0 /var/www/html/src/Database.php(107): PDOStatement->execute(Array) #1 /var/www/html/src/Database.php(93): Database->fetch('SELECT value FR...', Array) #2 /var/www/html/src/Route.php(319): Database->fetchSetting('killswitch') #3 /var/www/html/src/Route.php(31): Route->verifySettings() #4 /var/www/html/index.php(35): Route->__construct() #5 {main} thrown in /var/www/html/src/Database.php on line 107

**Comment by wdsjxh** [comment]
请问是不是dockerfile中没有定义生成具体表结构，我直接登录PHPadmin，只有数据库名，没有具体的表
